
["Config category"]
	#Set the clients minimum memory warning threshold in MB. Choose the lowest value possible which keeps the pack playable.
	#Range: 2500 ~ 25000
	minimumClient = 2500
	#Set the clients maximum memory warning threshold in MB. Choose a generous maximum with some additional over the required, e.g.recommended is 6000mb then set this to ~8000mb
	#Range: 2500 ~ 60000
	maximumClient = 8500
	#Set the servers minimum memory warning threshold in MB. Choose the lowest value possible which keeps the pack playable.
	#Range: 2500 ~ 25000
	minimumServer = 2500
	#Set the servers maximum memory warning threshold in MB. Choose a generous maximum with some additional over the required, e.g.recommended is 6000mb then set this to ~8000mb
	#Range: 2500 ~ 600000
	maximumServer = 8500
	#Disable the memory warnings, default = false
	disableWarnings = true
	#Set the link used to guide players to a website with instructions to change memory allocation
	howtolink = "https://apexminecrafthosting.com/how-to-allocate-more-ram/"

